import {Link} from 'react-router-dom';import {ArrowRight} from 'lucide-react';import {areas} from '../content/areas';import {articles} from '../content/articles';import {settings} from '../content/settings';
export default function Home({lang,t}){const prefix=lang==='en'?'/en':'';return <>
<section className="hero"><div className="hero-copy"><p className="eyebrow">{t.hero.eyebrow}</p><h1>{t.hero.title}</h1><p className="lead">{t.hero.body}</p><div className="actions"><a className="button" href={settings.calendar} target="_blank" rel="noreferrer">{t.hero.primary}</a><Link className="button outline" to={`${prefix}/areas`}>{t.hero.secondary}</Link></div></div><div className="hero-image"><img src="/images/paola-hero.webp" alt="Paola Leite Eikeset"/></div></section>
<section className="stats">{t.stats.map(([a,b])=><div key={a}><strong>{a}</strong><span>{b}</span></div>)}</section>
<section className="approach"><div className="image-panel"><img src="/images/paola-approach.webp" alt="Paola Leite Eikeset a trabalhar"/></div><div className="text-panel"><p className="eyebrow">{t.approach.kicker}</p><h2>{t.approach.title}</h2>{t.approach.body.map(x=><p key={x}>{x}</p>)}<Link className="text-link" to={`${prefix}/quem-sou`}>{t.approach.button}<ArrowRight size={17}/></Link></div></section>
<section className="areas-home"><div className="section-head"><div><p className="eyebrow">01 — 08</p><h2>{t.areasTitle}</h2><p>{t.areasIntro}</p></div><Link className="text-link" to={`${prefix}/areas`}>{t.more}<ArrowRight size={17}/></Link></div><div className="area-list">{areas.map((a,i)=><Link to={`${prefix}/areas/${a.slug}`} className="area-row" key={a.slug}><span>{String(i+1).padStart(2,'0')}</span><h3>{a[lang].title}</h3><p>{a[lang].short}</p><ArrowRight/></Link>)}</div></section>
<section className="articles-section"><div className="section-head"><div><p className="eyebrow">Journal</p><h2>{t.articlesTitle}</h2><p>{t.articlesIntro}</p></div><Link className="text-link" to={`${prefix}/artigos`}>{t.allArticles}<ArrowRight size={17}/></Link></div><div className="article-grid">{articles.map(a=><Link className="article-card" to={`${prefix}/artigos/${a.slug}`} key={a.slug}><img src={a.image} alt=""/><small>{a.category[lang]} · {new Date(a.date).toLocaleDateString(lang==='pt'?'pt-PT':'en-GB')}</small><h3>{a.title[lang]}</h3><p>{a.summary[lang]}</p><span>{t.read} →</span></Link>)}</div></section>
<section className="cta"><img src="/images/paola-contact.webp" alt="Paola Leite Eikeset"/><div><p className="eyebrow">Contact</p><h2>{t.contactTitle}</h2><p>{t.contactBody}</p><div className="actions"><Link className="button" to={`${prefix}/contacto`}>{t.nav.contact}</Link><a className="button outline" href={settings.calendar} target="_blank" rel="noreferrer">{t.nav.schedule}</a></div></div></section>
</>}
