export const areas = [
 {slug:'direito-internacional',pt:{title:'Direito Internacional',short:'Soluções jurídicas transfronteiriças para particulares e empresas.',quote:'Quando os interesses atravessam fronteiras, o direito também deve acompanhá-los.'},en:{title:'International Law',short:'Cross-border legal solutions for individuals and businesses.',quote:'When interests cross borders, the law must follow them.'}},
 {slug:'fiscalidade-nordica',pt:{title:'Fiscalidade Nórdica',short:'Dupla tributação, residência fiscal e obrigações entre jurisdições.',quote:'Cada decisão fiscal deve ser pensada nos dois lados da fronteira.'},en:{title:'Nordic Tax Law',short:'Double taxation, tax residence and cross-border obligations.',quote:'Every tax decision must be considered on both sides of the border.'}},
 {slug:'direito-do-trabalho',pt:{title:'Direito do Trabalho',short:'Relações laborais em Portugal e em contexto internacional.',quote:'O trabalho internacional exige segurança jurídica em cada decisão.'},en:{title:'Employment Law',short:'Employment matters in Portugal and international contexts.',quote:'International work requires legal certainty in every decision.'}},
 {slug:'direito-civil',pt:{title:'Direito Civil',short:'Contratos, responsabilidade civil, património e litígios.',quote:'Prevenir um conflito é tão importante quanto resolvê-lo.'},en:{title:'Civil Law',short:'Contracts, civil liability, assets and disputes.',quote:'Preventing a dispute is as important as resolving it.'}},
 {slug:'familia-sucessoes',pt:{title:'Direito de Família e Sucessões',short:'Família, responsabilidades parentais, heranças e sucessões.',quote:'As questões familiares exigem rigor jurídico e sensibilidade humana.'},en:{title:'Family and Succession Law',short:'Family matters, parental responsibilities, inheritance and succession.',quote:'Family matters require legal rigour and human sensitivity.'}},
 {slug:'empresas-sociedades',pt:{title:'Direito de Empresas e Sociedades',short:'Constituição, contratos e acompanhamento jurídico empresarial.',quote:'Empresas sólidas começam com decisões juridicamente seguras.'},en:{title:'Corporate and Company Law',short:'Incorporation, contracts and ongoing corporate legal assistance.',quote:'Strong businesses begin with legally sound decisions.'}},
 {slug:'direito-maritimo',pt:{title:'Direito Marítimo',short:'Assessoria jurídica no setor marítimo e em operações internacionais.',quote:'O setor marítimo exige segurança jurídica em cada operação.'},en:{title:'Maritime Law',short:'Legal assistance for the maritime sector and international operations.',quote:'The maritime sector requires legal certainty in every operation.'}},
 {slug:'traducoes-certificadas',pt:{title:'Traduções Certificadas',short:'Traduções oficiais com validade jurídica em Portugal e no estrangeiro.',quote:'Uma tradução oficial preserva as palavras e o valor jurídico do documento.'},en:{title:'Certified Translations',short:'Official translations with legal validity in Portugal and abroad.',quote:'An official translation preserves both the words and the legal value of a document.'}}
]
