export const content = {
 pt: {
  nav:{home:'Início',about:'Quem Sou',areas:'Áreas de Atuação',articles:'Artigos',contact:'Contacto',schedule:'Agendar Consulta'},
  hero:{eyebrow:'Direito Internacional • Fiscalidade Nórdica • Traduções Certificadas',title:'Soluções jurídicas entre Portugal e os Países Nórdicos.',body:'Acompanhamento jurídico estratégico para particulares e empresas, com rigor, proximidade e visão internacional.',primary:'Agendar Consulta',secondary:'Conhecer os Serviços'},
  stats:[['+10 anos','de experiência'],['Portugal','Países Nórdicos'],['Consultas','presenciais e online'],['Português • Inglês','Norueguês']],
  approach:{kicker:'A nossa abordagem',title:'Uma abordagem jurídica sem fronteiras',body:['Cada situação jurídica envolve pessoas, empresas e patrimónios sujeitos a diferentes sistemas legais.','O acompanhamento é próximo, estratégico e rigoroso, com soluções claras para decisões mais seguras.'],button:'Conhecer a minha abordagem'},
  areasTitle:'Áreas de Especialização',areasIntro:'Assessoria jurídica integrada em matérias nacionais e transfronteiriças.',articlesTitle:'Centro de Conhecimento',articlesIntro:'Informação jurídica clara para decisões mais seguras.',contactTitle:'Vamos falar sobre o seu caso',contactBody:'Consultas presenciais no Porto e online para clientes em Portugal e nos Países Nórdicos.',send:'Enviar pedido para análise',name:'Nome',email:'Email',phone:'Telefone',subject:'Assunto',message:'Descreva brevemente a situação',privacy:'Ao enviar, confirma que leu a Política de Privacidade.',footer:'Direito Internacional • Fiscalidade Nórdica • Traduções Certificadas',read:'Ler artigo',more:'Saber mais',allArticles:'Ver todos os artigos',whatsapp:'Fale comigo no WhatsApp'},
 en: {
  nav:{home:'Home',about:'About',areas:'Practice Areas',articles:'Articles',contact:'Contact',schedule:'Schedule a Consultation'},
  hero:{eyebrow:'International Law • Nordic Tax Law • Certified Translations',title:'Legal solutions between Portugal and the Nordic countries.',body:'Strategic legal assistance for individuals and businesses, delivered with rigour, proximity and an international perspective.',primary:'Schedule a Consultation',secondary:'Explore Services'},
  stats:[['10+ years','of experience'],['Portugal','Nordic Countries'],['Consultations','in person and online'],['Portuguese • English','Norwegian']],
  approach:{kicker:'Our approach',title:'A legal approach without borders',body:['Every legal matter involves people, businesses and assets subject to different legal systems.','The work is close, strategic and rigorous, providing clear solutions for safer decisions.'],button:'Discover my approach'},
  areasTitle:'Practice Areas',areasIntro:'Integrated legal assistance in domestic and cross-border matters.',articlesTitle:'Knowledge Centre',articlesIntro:'Clear legal information for safer decisions.',contactTitle:'Let us discuss your case',contactBody:'In-person consultations in Porto and online assistance for clients in Portugal and the Nordic countries.',send:'Send request for review',name:'Name',email:'Email',phone:'Phone',subject:'Subject',message:'Briefly describe the matter',privacy:'By submitting, you confirm that you have read the Privacy Policy.',footer:'International Law • Nordic Tax Law • Certified Translations',read:'Read article',more:'Learn more',allArticles:'View all articles',whatsapp:'Chat with me on WhatsApp'}
}
